/* ═══════════════════════════════════════════════════════
   LED · data.js — Dados dos equipamentos (fonte: Excel)
   Futuramente substituído por chamadas à API MongoDB/Node.js
═══════════════════════════════════════════════════════ */

const DATA = {

  /* ── Multimédia ──────────────────────────────────────── */
  multimedia: [
    { kit: "Kc01",       qty: 1,  desc: "Kit de Chroma Key c/ 5 fundos coloridos e sistema de iluminação" },
    { kit: "Mmvm01",     qty: 1,  desc: "Mesa de mistura de vídeo multiformato HD - Roland V-02HD" },
    { kit: "Pcv01",      qty: 1,  desc: "Placa de captura de video HDMI-USB" },
    { kit: "Cds01",      qty: 1,  desc: "Controlador Deck Stream" },
    { kit: "Mma01",      qty: 1,  desc: "Mesa de mistura de audio com 2 colunas Yamaha Stagepas 400BT" },
    { kit: "Mfb01",      qty: 1,  desc: "Máquina Fotográfica Bridge PANASONIC Lumix DC-FZ82EG-K" },
    { kit: "Mpc01",      qty: 1,  desc: "Microfone para câmara fotográfica (externo)" },
    { kit: "CvSONY01",   qty: 1,  desc: "Câmara de vídeo SONY FDR-AX53 BOSS 4K Ultra HD" },
    { kit: "Dtp01",      qty: 1,  desc: "Datavideo Teleponto TP-500 DSLR Prompter" },
    { kit: "Tripe01",    qty: 1,  desc: "Tripé Traveler BRESSER TR-688V com Cabeça Giratória" },
    { kit: "Msf01",      qty: 1,  desc: "Microfones sem fios - Saramonic Blink 500 B2" },
    { kit: "Mft01",      qty: 1,  desc: "Microfone com fios e tripé - Shure SM58 - Set" },
    { kit: "Grav01",     qty: 1,  desc: "Gravador de Audio - Zoom H5 c/ cartão SD de 32 GB" },
    { kit: "Mdc01",      qty: 1,  desc: "WACOM Mesa Digitalizadora M com Caneta 4K Intuos, Bluetooth, Preto" },
    { kit: "Impre3D01",  qty: 1,  desc: "Impressora 3D - Blocks One MkII" },
    { kit: "Cdi3d01",    qty: 1,  desc: "Consumíveis diversos para impressora 3D (filamentos 1kg)" },
    { kit: "CPBCP01",    qty: 1,  desc: "Carregadores para Portátil Boltx0505 CLASSMATE PC" },
    { kit: "AV01",       qty: 1,  desc: "Auscultadores Vox505" },
    { kit: "KMSFL01",    qty: 1,  desc: "Kit Microfone sem fios de Lapela" },
    { kit: "SPSSDT01",   qty: 1,  desc: "Samsung Portable SSD T7" },
    { kit: "Usbcmd01",   qty: 1,  desc: "USB-C to Multiport Dock 8 in 1" },
  ],

  /* ── Programação & Robótica ──────────────────────────── */
  robotica: [
    { kit: "Pep01",      qty: 1,  desc: "Portáteis de elevada performance" },
    { kit: "Mbik01",     qty: 1,  desc: "BBC Micro:bit Inventor's Kit com Acessórios v2" },
    { kit: "KSM01",      qty: 1,  desc: "KIT 37 SENSORES E ATUADORES PARA MICRO:BIT - KEYESTUDIO KS0361" },
    { kit: "Kdie01",     qty: 1,  desc: "Kit de desenvolvimento e iniciação electrónica + Arduino UNO Rev3 Compatível" },
    { kit: "Aunorc",     qty: 1,  desc: "Arduino UNO Rev3 Compatível" },
    { kit: "Kscar01",    qty: 1,  desc: "Kit de 37 sensores compatível com Arduino e Raspberry Pi" },
    { kit: "LESps01",    qty: 1,  desc: "LEGO Education SPIKE Prime Set" },
    { kit: "CeK01",      qty: 1,  desc: "Conjunto de expansão do kit anterior com 603 peças" },
    { kit: "KDEA01",     qty: 1,  desc: "KIT DOMÓTICA EDUCACIONAL PARA ARDUINO - KEYESTUDIO KS0085" },
    { kit: "Breadb",     qty: 1,  desc: "Breadboard com mínimo de 830 furos" },
    { kit: "Smp",        qty: 1,  desc: "Stepper Motor de Passo" },
    { kit: "Duln",       qty: 1,  desc: "Driver ULN2003 para Stepper Motor" },
    { kit: "Ledvl01",    qty: 5,  desc: "LED Vermelho 5mm" },
    { kit: "Ledv01",     qty: 5,  desc: "LED Verde 5mm" },
    { kit: "Leda01",     qty: 5,  desc: "LED Amarelo 5mm" },
    { kit: "Sdv01",      qty: 2,  desc: "Sensor de Vibração" },
    { kit: "Scf",        qty: 1,  desc: "Sensor de Chama ou Fogo" },
    { kit: "Stlm",       qty: 1,  desc: "Sensor de Temperatura LM35" },
    { kit: "Riir",       qty: 1,  desc: "Recetor de Infravermelhos IR" },
    { kit: "Slldr01",    qty: 3,  desc: "Sensor de Luz LDR" },
    { kit: "Cbp01",      qty: 4,  desc: "Cápsula para Botão de Pressão" },
    { kit: "Bp01",       qty: 4,  desc: "Botão de Pressão" },
    { kit: "Pl10k",      qty: 1,  desc: "Potenciómetro Linear 10K" },
    { kit: "Buzzp",      qty: 1,  desc: "Buzzer Passivo (piezo buzzer)" },
    { kit: "Buzza",      qty: 1,  desc: "Buzzer Ativo (tone generator)" },
    { kit: "Ciir",       qty: 1,  desc: "Comando Infravermelho IR" },
    { kit: "Dlcd",       qty: 1,  desc: "Display LCD 16x02" },
    { kit: "Sm90",       qty: 1,  desc: "Servo Motor SG90" },
    { kit: "Mled",       qty: 1,  desc: "Matriz LED 8x8" },
    { kit: "Dled7s1d",   qty: 1,  desc: "Display LED 7 Segmentos de 1 Dígito" },
    { kit: "Dled7s4d",   qty: 1,  desc: "Display LED 7 Segmentos de 4 Dígitos" },
    { kit: "Rohm01",     qty: 10, desc: "Resistência 220 Ohm" },
    { kit: "Rohm1k01",   qty: 10, desc: "Resistência 1K Ohm" },
    { kit: "Rohm10k01",  qty: 10, desc: "Resistência 10K Ohm" },
    { kit: "Cljmmb01",   qty: 30, desc: "Cabos de Ligação Jumper Macho-Macho para Breadboard" },
    { kit: "Clbmf01",    qty: 10, desc: "Cabos de Ligação Jumper para Breadboard Macho-Fêmea" },
    { kit: "Caixa01",    qty: 1,  desc: "Caixa de equipamentos de Programação e Robótica PR.FT7_5" },
    { kit: "Caixa02",    qty: 1,  desc: "Caixa de equipamentos de Programação e Robótica PR.FT8_5" },
    { kit: "Caixa03",    qty: 1,  desc: "Caixa de equipamentos de Programação e Robótica PR.FT9_5" },
    { kit: "Caixa04",    qty: 1,  desc: "Caixa de equipamentos de Programação e Robótica PR.FT10_10" },
    { kit: "Caixa05",    qty: 1,  desc: "Caixa de equipamentos de Programação e Robótica PR.FT11_5" },
    { kit: "PdCp",       qty: 1,  desc: "Placa de Control principal (compatível com Arduino UNO Rev3)" },
    { kit: "Emsc",       qty: 1,  desc: "Estrutura em madeira de simulação de uma casa" },
    { kit: "MB",         qty: 1,  desc: "Módulo Bluetooth (DX-BT24)" },
    { kit: "Msm",        qty: 2,  desc: "Módulo servo motor" },
    { kit: "Md",         qty: 1,  desc: "Módulo display LCD 1602" },
  ],

  /* ── STEM ────────────────────────────────────────────── */
  stem: [
    { kit: "Mek01",     qty: 1, desc: "Mbot Explorer Kit Makeblock com Display" },
    { kit: "BatMbot01", qty: 1, desc: "Bateria de lítio para MBot" },
    { kit: "Mbss01",    qty: 1, desc: "Makeblock (Mbot) módulo sensor de Som" },
    { kit: "Mbsg01",    qty: 1, desc: "Makeblock (Mbot) módulo sensor de Gás" },
    { kit: "Mbsth01",   qty: 1, desc: "Makeblock (Mbot) módulo sensor de Temperatura e humidade" },
    { kit: "Mbsc01",    qty: 1, desc: "Makeblock (Mbot) módulo sensor de Cor" },
    { kit: "Mbsts01",   qty: 1, desc: "Makeblock (Mbot) módulo sensor de Temperatura submergível" },
    { kit: "Mbsm01",    qty: 1, desc: "Makeblock (Mbot) módulo sensor de Movimento" },
    { kit: "Mbsl01",    qty: 1, desc: "Makeblock (Mbot) módulo sensor de Luz" },
    { kit: "Micro01",   qty: 1, desc: "Microscópio B-190TB c/ câmara digital" },
    { kit: "Opcm01",    qty: 1, desc: "Optika Câmera C-B1, color, CMOS, 1/3\", 1.3 MP, USB2.0" },
    { kit: "Tiib01",    qty: 1, desc: "TI-Innovator™ Hub com TI LaunchPad™ Board" },
    { kit: "Tiir01",    qty: 1, desc: "TI-Innovator™ Rover" },
    { kit: "Ler01",     qty: 1, desc: "Laboratório Energias Renováveis" },
    { kit: "Titec01",   qty: 1, desc: "TI-Innovator™ Technology" },
  ],
};
